version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 4300:3306
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    tty: true
    stdin_open: true
    volumes:
      - .:/google_maps_platform_sample
    ports:
      - '3000:3000'
    depends_on:
      - db
volumes:
  mysql-data:
